### ISSUE TITLE
Algorithms/procedures

### ISSUE THREAD

**Issue by nareshmuppalaneni** [kste/cryptosmt#5]
Dear Author, 
May I know how the tool was developed. What are different algorithms used. Can you explain what are the steps involved.What is the input for SMT, from there what is the output to STP/cryptominisat

**Comment by git2109** [comment]
Hi, what is the role of python language in this smt solver?

**Comment by hadipourh** [comment]
Hi!
For your information, CryptoSMT is not actually an SMT solver. It is actually a cryptographic tool which uses some SMT solvers such as [STP](https://github.com/stp/stp), and [Boolector](https://boolector.github.io/), to solve some kinds of cryptographic problems.  In other words, CryptoSMT uses Python language to create an SMT model, and then invokes an SMT solver to solve the obtained STP model. Therefore, the main role of CryptoSMT is converting a cryptographic problem to an SMT model, and uses Python language to do that. 
Good luck!

**Comment by git2109** [comment]
با سلام و تشکر از نکاتی که مرقوم فرمودید. من در حال کار روی یک تحلیل رمز با استفاده از حل کننده 
STP 
هستم. بسیار خوشحال شدم از اینکه بالاخره کسی پیدا شد که در این زمینه نسبتا خاص تبحر داشته باشه. اگر امکان داره برای درک بهتر یکی دو نکته دیگه از کارم که در مقاله اصلی خیلی خلاصه ذکر شده مزاحم وقتتان بشم.



    On Sunday, April 12, 2020, 12:26:50 AM GMT+4:30, Hosein Hadipour <notifications@github.com> wrote:  
 
 


Hi!
For your information, CryptoSMT is not actually an SMT solver. It is actually a cryptographic tool which uses some SMT solvers such as STP, and Boolector, to solve some kinds of cryptographic problems. In other words, CryptoSMT uses Python language to create an SMT model, and then invokes an SMT solver to solve the obtained STP model. Therefore, the main role of CryptoSMT is converting a cryptographic problem to an SMT model, and uses Python language to do that.
Good luck!

**Comment by hadipourh** [comment]
درود،
مشکلی نیست ایمل من را می‌توانید در حساب گیت هاب بنده پیدا کنید.
موفق باشید،
حسین

**Comment by git2109** [comment]
عنوان مقاله اینه:
Observations on the SIMON block cipher 
family"

 اما سوال من: در صحات اولیه مقاله ک مربوط به رمز سبک وزن سایمون هست برای تابع دور با استفاده از یک سری معادلات یک رابطه هم ارز بدست آورده . خواستم ببینم دقیقا چجوری بدست آورده؟
هم ارزی مذکور به صورت زیره:
 f (x) = x&; S
d
(x) from fa, b, c (x) =s
a
(x) & s
b
(x) + S
c
(x) 


     On Sunday, April 12, 2020, 12:26:50 AM GMT+4:30, Hosein Hadipour <notifications@github.com> wrote:  
 
 


Hi!
For your information, CryptoSMT is not actually an SMT solver. It is actually a cryptographic tool which uses some SMT solvers such as STP, and Boolector, to solve some kinds of cryptographic problems. In other words, CryptoSMT uses Python language to create an SMT model, and then invokes an SMT solver to solve the obtained STP model. Therefore, the main role of CryptoSMT is converting a cryptographic problem to an SMT model, and uses Python language to do that.
Good luck!
