### ISSUE TITLE
S2 rotate in simon

### ISSUE THREAD

**Issue by nareshmuppalaneni** [kste/cryptosmt#7]
in simon.py line 87 i think the argument for right rotate for 6 is wrong, 
we need to rotate left for twice only S2

def getDependentBitsForAND(self, x_in, wordsize):
        "rotate_right(diff, 6) & (~rotate_left(diff, 1)) & rotate_left(diff, 8);"
        command = "({0} & (~{1}) & {2})".format(StpCommands().getStringRightRotate(x_in, 6, wordsize),
                                              StpCommands().getStringLeftRotate(x_in, 1, wordsize),
                                              StpCommands().getStringLeftRotate(x_in, 8, wordsize));
        return command

**Comment by nareshmuppalaneni** [comment]
In Simond round getStringForSimonRound function  what for this code
#More improved 
        command += "ASSERT({0} = (IF {2} = 0x{4} THEN BVSUB({5},0x{4},0x{6}1) ELSE BVXOR(~{1} & ~{2} & {3}, {2}) ENDIF));".format(w, StpCommands().getStringRightRotate(x_in, 7, wordsize),
 x_in, StpCommands().getStringRightRotate(x_in, 14, wordsize),
                                                                          "f"*(wordsize / 4), wordsize, "0"*((wordsize / 4)- 1));

**Comment by kste** [comment]
This was slightly changed in the latest version, so you might want to have a look at the current version.

This part computes the differential probability for one round. The if/then/else is needed to deal with the special case when you have a difference of 0xFF...FF.

**Comment by kste** [comment]
A clear description of this can now be found in http://eprint.iacr.org/2015/145
