### ISSUE TITLE
Role of Weight component in cryptoSMT

### ISSUE THREAD

**Issue by nareshmuppalaneni** [kste/cryptosmt#8]
What is the role of weight in cryptoSMT
What does it mean that weight is equals to hamming weight of the given variables.

**Comment by kste** [comment]
The weight corresponds to the probability of the differential characteristic. For instance that if you have found a characteristic with a weight of 20 than the probability that a plaintext pair follows exactly this path is 2^{-20}.
The weight for each round is stored in a variable w_i and the probabilty for this round is than 2^{-hw(w_i)}.
