### ISSUE TITLE
Site not found

### ISSUE THREAD

**Issue by pfasante** [kste/cryptosmt#9]
http://kste.github.io/cryptosmt/ cannot be displayed (referred to in the short description).

**Comment by kste** [comment]
Thanks for pointing this out. I updated it now to the new project website http://www2.compute.dtu.dk/~stek/cryptosmt.html

**Comment by 16121308** [comment]
> Thanks for pointing this out. I updated it now to the new project website http://www2.compute.dtu.dk/~stek/cryptosmt.html

This website cannot be displayed neither with a mistake saying
 "I couldn't find the requested URL      
 /~stek/cryptosmt.html   
There is no such user: stek"
